eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://localhost:9091/eureka/
management:
    security:
        enabled: false
server:
    port: 8661
spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/Kgharte/Config-Server-Repo
